name: Main CI Pipeline

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'app.py'
      - 'Dockerfile'
      - 'requirements.txt'
      - 'docker-compose.yml'
      - 'templates/**'
      - 'db/**'
      - '.github/workflows/**'
    
permissions:
  contents: read
  pull-requests: read

jobs:
  call-security-check:
    uses: ./.github/workflows/python-security-check.yml

  docker-build:
    needs: call-security-check
    uses: ./.github/workflows/docker-build-push.yml
    with:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  
  deploy-to-ec2:
    needs: docker-build
    uses: ./.github/workflows/deploy_to_ec2.yml
    with:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
    secrets:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }} 
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}